def executar(dados):
    print("\n===== DECISÃO DA IA =====")
    print(f"Direção: {dados.get('direcao')}")
    print(f"Estrutura: {dados.get('estrutura')}")
    print(f"Liquidez: {dados.get('liquidez')}")
    print(f"Imbalance: {dados.get('imbalance')}")
    print(f"Entrada: {dados.get('entrada')}")
    print(f"Stop: {dados.get('stop')}")
    print(f"TP: {dados.get('tp')}")
    print(f"Motivo: {dados.get('motivo')}")
